Branch2
MdSaib/helloMicroverse pull request #1
Opened 2022-01-04 17:08 UTC by MdSaib

# change text color in style.css

2022-01-04 18:02 UTC, julie-ify requested changes
## Hi @MdSaib, 

Good job so far! 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the review comments below ._

- [ ] Good job so far 👍. However, consider making your Pull Request description more descriptive by adding a descriptive title telling you what changes are inside. and also a short summary describing introduced changes in more details. Check out this [link ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to learn how to write a good pull request description and good commit messages 😄

- [ ] Consider adding `node_modules` directory to `.gitignore` as it can be added by accident while setting up linters and also removing the duplicate `test.md` in your `.gitignore` file.

- [ ] Please consider giving your feature branch a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). This is to make your branch name more descriptive and make your repository more professional. This is to be implemented moving forward in your new projects 😃

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-04 18:02 UTC, julie-ify commented on README.md
> +I will do it after first code review.
- [ ] Consider adding a descriptive README to your repository. This is because the README is where the description of your project, project overview, and project prerequisites are being added so that visitors to your repository could see them. Please consider adding a good and descriptive README using this [template](https://github.com/microverseinc/readme-template/blob/master/README.md)

2022-01-05 09:08 UTC, MdSaib commented
# update README.md using microverse's template.

# remove duplicate test.md in .gitignore file.
# add node_modules in .gitignore file

2022-01-05 09:55 UTC, andersonlebon requested changes
Hi @MdSaib 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
## Required Changes ♻️

- [ ] Good job on adding a description to your Pull request however, I think it would be better to list these tasks with dashes or something else rather than using headings. 

- [ ] Also it would look better if you add an introductive sentence in the pull request description. 
A template example
```
In this pull request, I managed the implementation of the following tasks: 

- [ ] update README.md using microverse's template.
- [ ] remove duplicate test.md in .gitignore file.
- [ ] add node_modules in .gitignore file

``` 

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 09:55 UTC, andersonlebon commented on README.md
> +- etc
- [ ] Kindly I would suggest customizing this section with your own information. This will help visitors know people you are grateful to.

2022-01-05 12:45 UTC, MdSaib commented
> ## Required Changes ♻️
> * [ ]  Good job on adding a description to your Pull request however, I think it would be better to list these tasks with dashes or something else rather than using headings.
> * [ ]  Also it would look better if you add an introductive sentence in the pull request description.
>   A template example
> 
> ```
> In this pull request, I managed the implementation of the following tasks: 
> 
> - [ ] update README.md using microverse's template.
> - [ ] remove duplicate test.md in .gitignore file.
> - [ ] add node_modules in .gitignore file



Sorry for the inconvenience. I don't understand how to do so!

 following the instruction you have given, should I edit my above comments, or I need to do a new comment on my pull request's conversation?

2022-01-05 13:03 UTC, MdSaib commented
In this pull request, I managed the implementation of the following tasks: 

- [ ] update README.md using microverse's template.
- [ ] solve linters' Styleint issue.
- [ ] remove duplicate test.md in .gitignore file.
- [ ] add node_modules in .gitignore file
- [ ] write original 'acknowledgement' in README.md file

2022-01-05 13:12 UTC, MdSaib commented
@andersonlebon 

pardon me. I am a beginner.

Is everything okay now?

Actually, I am not sure where is the "pull request description"? 

Is it the below one?
 "add linters, add html-css, add test.md, add .gitignore. #1" 
 Do I need to change that?
 
 ot, just commenting on pull request conversion is mean to be count as "pull request description"?

2022-01-05 16:28 UTC, MdSaib commented
In this pull request, I managed the implementation of the following tasks: 

- [ ] update README.md using microverse's template.
- [ ] remove duplicate test.md in .gitignore file.
- [ ] add node_modules in .gitignore file

2022-01-07 02:00 UTC, andersonlebon commented
Hello, @MdSaib Your project is now okay everything is good you can submit it.

2022-01-07 02:17 UTC, andersonlebon approved these changes
Hi @MdSaib 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-07 02:30 UTC, merged